"use client";
import { useMemo, useState } from "react";
import { wikiItems, type WikiItem } from "./wiki-data";

const labels:Record<string,string>={Hair:"髮型",HairAccessory:"髮飾",HeadAccessory:"頭飾",Mask:"面具",FaceAccessory:"臉部配件",Necklace:"頸飾",Cape:"斗篷",Outfit:"服裝",OutfitShoes:"服裝＋鞋",Shoes:"鞋子",Instrument:"樂器",Prop:"道具",Furniture:"家具",Emote:"動作",Stance:"站姿",Call:"叫聲"};
const types=["全部","Cape","Hair","Mask","Outfit","Shoes","HairAccessory","FaceAccessory","Necklace","Prop","Furniture","Emote"];
const sources:Record<string,string>={"全部來源":"全部來源",seasons:"季節",events:"活動",realms:"常駐地圖",store:"商店",base:"基礎"};
const tip=(t:string)=>({Cape:"先看整體輪廓，再比對下襬形狀、肩部裝飾與主色。正面和背面經常不同。",Hair:"先看瀏海和後腦輪廓，再找辮子、耳側髮束或特殊髮飾。",Mask:"注意眼睛開口、額頭圖案、鼻嘴區域與面具外框。",Outfit:"由領口、袖型、腰線與褲管比對，不要只靠顏色判斷。",Shoes:"優先看鞋筒高度、鞋頭形狀和腳踝裝飾。",HairAccessory:"確認配件位於頭頂、耳側或後腦，再比較左右對稱性。",Prop:"分辨背負與擺放後的外型，兩種狀態可能差很多。",Furniture:"以外框、功能部件與比例辨識，顏色只作輔助。",Emote:"看起始姿勢、手臂方向和特效，單張圖示只適合初步比對。"}[t]||"先看輪廓與所在位置，再比對局部裝飾；不要只依顏色下結論。");
const seasonZh:Record<string,string>={gratitude:"感恩季",lightseekers:"追光季",belonging:"歸屬季",rhythm:"音韻季",enchantment:"魔法季",sanctuary:"聖島季",prophecy:"預言季",dreams:"夢想季",assembly:"重組季","the-little-prince":"小王子季",flight:"飛行季",abyss:"潛海季",performance:"表演季",shattering:"破碎季",aurora:"極光季",remembrance:"緬懷季",passage:"夜行季",moments:"拾光季",revival:"歸巢季","nine-colored-deer":"九色鹿季",nesting:"築巢季",duets:"協奏季",moomin:"姆明季",radiance:"染色季","blue-bird":"青鳥季","two-embers-part-1":"暮星季",lightmending:"織光季",migration:"遷徙季",carnival:"狂歡季","dear-van-gogh":"致梵谷季"};
const seasons=Object.entries(seasonZh);
const source=(x:WikiItem)=>x.section==="seasons"?`季節 · ${seasonZh[x.collection]||x.collection.replaceAll("-"," ")}`:`${sources[x.section]||x.section} · ${x.collection.replaceAll("-"," ")}`;
const exactZh:Record<string,string>={"Little Prince Ultimate Hair":"小王子畢業髮型","Little Prince Ultimate Outfit":"小王子畢業服裝","Little Prince Ultimate Rose":"小王子畢業玫瑰","Sword Outfit":"劍士服","Anubis Mask":"阿努比斯面具","Owl Hair":"白鳥髮型","Penguin Hair":"白梟髮型","Rhythm Ultimate Hair":"白鳥髮型","Performance Ultimate Hair":"白梟髮型","Wasteland Elder Hair":"龍骨髮型","Forest Elder Hair":"雨林長老髮型（雨媽）","Valley Elder Hair 1":"霞谷長老髮型 1","Valley Elder Hair 2":"霞谷長老髮型 2","Vault Elder Hair":"禁閣長老髮型","Prairie Elder Hair":"雲野長老髮型","Isle Elder Hair":"晨島長老髮型","Nine-Colored Deer Ultimate Hair":"九色鹿畢業髮型","Grand Piano":"高音鋼琴","Manta Cape":"遙鯤斗篷","Chibi Mask":"矮人面具","Faceless Mask":"無臉面具","Rainbow Cape":"彩虹斗篷","White Cape":"白斗篷","Black Cape":"黑斗篷","Red Cape":"紅斗篷","Blue Cape":"藍斗篷","Pink Cape":"粉紅斗篷","Green Cape":"綠斗篷","Yellow Cape":"黃斗篷"};
const words:Record<string,string>={Ultimate:"畢業",Elder:"長老",Seasonal:"季節",Little:"小",Prince:"王子",Nine:"九",Colored:"色",Deer:"鹿",Anubis:"阿努比斯",Aurora:"極光",Moomin:"姆明",Cinnamoroll:"大耳狗",Journey:"旅人",Rainbow:"彩虹",Bloom:"花憩",Fortune:"福瑞",Nature:"自然",Mischief:"惡作劇",Feast:"宴會",Love:"愛之日",Sunlight:"陽光",Moonlight:"月光",Music:"音樂",Style:"時尚",Anniversary:"週年",Tournament:"錦標賽",Hair:"髮型",Hairstyle:"髮型",Cape:"斗篷",Mask:"面具",Outfit:"服裝",Shoes:"鞋子",Slippers:"拖鞋",Boots:"靴子",Hat:"帽子",Hood:"兜帽",Crown:"皇冠",Tiara:"頭冠",Headband:"頭帶",Hairpin:"髮夾",Accessory:"配件",Necklace:"項鍊",Pendant:"吊墜",Scarf:"圍巾",Earrings:"耳環",Glasses:"眼鏡",Goggles:"護目鏡",Piano:"鋼琴",Guitar:"吉他",Harp:"豎琴",Flute:"笛子",Drum:"鼓",Umbrella:"雨傘",Lantern:"燈籠",Table:"桌子",Chair:"椅子",Tent:"帳篷",Prop:"道具",Plush:"玩偶",Doll:"娃娃",Flower:"花朵",Rose:"玫瑰",Star:"星星",Moon:"月亮",Sun:"太陽",Cloud:"雲朵",Manta:"遙鯤",Bird:"鳥",Butterfly:"蝴蝶",Rabbit:"兔子",Fox:"狐狸",Cat:"貓咪",Dragon:"龍",White:"白色",Black:"黑色",Red:"紅色",Blue:"藍色",Green:"綠色",Yellow:"黃色",Pink:"粉紅色",Purple:"紫色",Orange:"橘色",Golden:"金色",Dark:"深色",Light:"淺色",Small:"小型",Large:"大型",HairAccessory:"髮飾",HeadAccessory:"頭飾",FaceAccessory:"臉部配件"};
const seasonWords:Record<string,string>={of:"之",Of:"之",The:"",the:"",a:"",Stone:"石頭",Dance:"舞蹈",Whisperer:"語者",Spin:"旋轉",Nesting:"築巢",Carnival:"狂歡",Lightmending:"織光",Radiance:"染色",Prophet:"先知",Dancer:"舞者",Memory:"回憶",Crab:"螃蟹",Rug:"地毯",Painting:"畫作",Clap:"鼓掌",Migrating:"遷徙",Face:"臉部",Parent:"家長",Sparkler:"煙火棒",Performer:"表演者",Assembly:"重組",Walk:"走路",Trick:"戲法",Jellyfish:"水母",Stance:"站姿",Balance:"平衡",Pleading:"祈求",Anxious:"焦慮",Remembrance:"緬懷",Juggler:"雜耍者",Call:"叫聲",Flight:"飛行",Flourishing:"蓬勃",Beginnings:"初始",Jolly:"歡樂",Tiptoeing:"踮腳",Marching:"行進",Grateful:"感恩",Passage:"夜行",Duet:"協奏",Duets:"協奏",Actor:"演員",Handshake:"握手",Scholar:"學者",Scarred:"傷痕",Cousin:"表親",Wise:"智慧",Provoking:"挑釁",Leaping:"跳躍",Wall:"牆面",Warrior:"戰士",Collector:"收藏家",Troupe:"劇團",Boogie:"舞步",Performance:"表演",Starry:"星光",Kiss:"親吻",Director:"導演",Pioneer:"先驅",Champion:"冠軍",Catcher:"捕捉者",Migration:"遷徙",Jelly:"果凍",Two:"雙",Poster:"海報",Manatee:"海牛",Vestige:"遺跡",Sentry:"哨兵",Grandparent:"祖父母",Inspiration:"靈感",Inclusion:"包容",Spirit:"先祖",Comfort:"安慰",Kindness:"善意",Medium:"中型",Plant:"植物",Nightbird:"夜鳥",Hacky:"踢球",Bearhug:"熊抱",Fire:"火焰",Piggyback:"背背",Abyss:"潛海",Neckpiece:"頸飾",Bask:"曬太陽",Slow:"緩慢",Frustration:"沮喪"};
const seasonItemNames=new Set(wikiItems.filter(x=>x.section==="seasons").map(x=>x.name));
const zhName=(name:string)=>{if(exactZh[name])return exactZh[name];if(!seasonItemNames.has(name))return"中文名待核對";const translated=name.replace(/[-–]/g," ").split(/\s+/).map(x=>seasonWords[x]||words[x]||x).join("");return`暫譯 · ${translated}`};

export default function Home(){
 const[q,setQ]=useState(""),[type,setType]=useState("全部"),[origin,setOrigin]=useState("全部來源"),[season,setSeason]=useState("全部季節"),[sort,setSort]=useState("new");
 const[selected,setSelected]=useState<WikiItem|null>(null);
 const[page,setPage]=useState(1);
 const filtered=useMemo(()=>{const rows=wikiItems.filter(x=>{const z=q.trim().toLowerCase();const seasonName=seasonZh[x.collection]||"";return(!z||x.name.toLowerCase().includes(z)||zhName(x.name).toLowerCase().includes(z)||String(x.id).includes(z)||x.collection.includes(z)||seasonName.includes(z))&&(type==="全部"||x.type===type)&&(origin==="全部來源"||x.section===origin)&&(season==="全部季節"||x.collection===season)});return [...rows].sort((a,b)=>sort==="old"?a.id-b.id:sort==="name"?zhName(a.name).localeCompare(zhName(b.name),"zh-Hant"):b.id-a.id)},[q,type,origin,season,sort]);
 return <main className="app-shell">
  <header className="topbar"><button className="brand"><span className="brand-star">✦</span><b>光遇辨識 Wiki</b></button><nav><button className="active">圖鑑</button></nav><button className="account" aria-label="帳號">●</button></header>
  <section className="catalog" id="top">
   <div className="search-row"><label className="search"><span>⌕</span><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="搜尋中文名稱、物品 ID 或季節"/><button onClick={()=>setPage(1)}>搜尋</button></label><label className="filter"><span>≡</span><select aria-label="來源篩選" value={origin} onChange={e=>{const value=e.target.value;setOrigin(value);if(value!=="seasons")setSeason("全部季節");setPage(1)}}>{Object.entries(sources).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="filter"><span>季</span><select aria-label="季節篩選" value={season} onChange={e=>{setSeason(e.target.value);if(e.target.value!=="全部季節")setOrigin("seasons");setPage(1)}}><option value="全部季節">全部季節</option>{seasons.map(([slug,name])=><option key={slug} value={slug}>{name}</option>)}</select></label></div>
   <div className="chips">{types.map(x=><button key={x} className={type===x?"selected":""} onClick={()=>{setType(x);setPage(1)}}>{x==="全部"?x:labels[x]}</button>)}</div>
   <div className="result-head"><h1>{season!=="全部季節"?seasonZh[season]:"找到"} {filtered.length.toLocaleString()} 件物品</h1><label>排序 <select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">最新 ID</option><option value="old">最舊 ID</option><option value="name">中文名稱</option></select></label></div>
   {filtered.length?<div className="grid">{filtered.slice(0,page*36).map(x=><button className="item-card" key={x.guid} onClick={()=>setSelected(x)}><div className="image-wrap"><img src={x.icon} alt={x.name} loading="lazy" referrerPolicy="no-referrer"/></div><div className="card-body"><div><span className={`type type-${x.type}`}>{labels[x.type]||x.type}</span><small>ID: {x.id}</small></div><h2>{zhName(x.name)}</h2><p className="english">{x.name}</p><p>{source(x)}</p></div></button>)}</div>:<div className="empty"><b>找不到符合的物品</b><span>試著縮短關鍵字或清除分類條件。</span></div>}
   {page*36<filtered.length&&<button className="more" onClick={()=>setPage(x=>x+1)}>載入更多</button>}
  </section>
  {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modal-images"><div><span>衣櫃圖示</span><img src={selected.icon} alt={selected.name} referrerPolicy="no-referrer"/></div>{selected.previewUrl&&<div><span>穿戴／實物預覽</span><img src={selected.previewUrl} alt={`${selected.name} 預覽`} referrerPolicy="no-referrer"/></div>}</div><div className="modal-content"><div className="modal-tag"><span className={`type type-${selected.type}`}>{labels[selected.type]}</span><small>ID: {selected.id}</small></div><h2>{zhName(selected.name)}</h2><p className="modal-english">{selected.name}</p><p className="source">{source(selected)}{selected.group?` · ${selected.group}`:""}</p><div className="recognition"><b>✦ 怎麼辨識</b><p>{tip(selected.type)}</p></div><dl><div><dt>資料 GUID</dt><dd>{selected.guid}</dd></div><div><dt>原始分類</dt><dd>{selected.type}</dd></div></dl>{selected.wiki&&<a className="wiki-link" href={selected.wiki} target="_blank" rel="noreferrer">查看原始 Wiki ↗</a>}</div></article></div>}
  <nav className="bottom-nav"><button className="active"><i>⌂</i><span>圖鑑</span></button><button disabled><i>☆</i><span>收藏</span></button></nav>
  <footer><b>光遇辨識 Wiki</b><span>資料來源：SkyGame-Data 1.3.5、SkyGame-Planner</span><span>非官方粉絲學習工具 · Finding Light in the Darkness</span></footer>
 </main>
}
