"use client";
import { useMemo, useState } from "react";
import { wikiItems, type WikiItem } from "./wiki-data";

const labels: Record<string,string>={Hair:"髮型",HairAccessory:"髮飾",HeadAccessory:"頭飾",Mask:"面具",FaceAccessory:"臉部配件",Necklace:"頸飾",Cape:"斗篷",Outfit:"服裝",OutfitShoes:"服裝＋鞋",Shoes:"鞋子",Instrument:"樂器",Prop:"道具",Furniture:"家具",Emote:"動作",Stance:"站姿",Call:"叫聲"};
const types=["全部","Cape","Hair","Mask","Outfit","Shoes","HairAccessory","FaceAccessory","Necklace","Prop","Furniture","Emote"];
const sources:Record<string,string>={"全部來源":"全部來源",seasons:"季節",events:"活動",realms:"常駐地圖",store:"商店",base:"基礎"};
const tip=(t:string)=>({Cape:"先看整體輪廓，再比對下襬形狀、肩部裝飾與主色。正面和背面常不同。",Hair:"先看瀏海與後腦勺輪廓，再找辮子、耳側髮束或特殊髮飾。",Mask:"注意眼睛開口、額頭圖案、鼻嘴區域與面具外框。",Outfit:"由領口、袖型、腰線與褲管四處比對；不要只靠顏色判斷。",Shoes:"優先看鞋筒高度、鞋頭和腳踝裝飾。",HairAccessory:"確認配件位於頭頂、耳側或後腦，並比對左右對稱性。",Prop:"分辨背負時與擺放後的外型，兩種狀態可能差很多。",Furniture:"以外框、功能部件與比例辨識，顏色只能當輔助線索。",Emote:"看起始姿勢、手臂方向和特效，單張圖示只適合初步比對。"}[t]||"先看輪廓與位置，再比對局部裝飾；不要只依顏色下結論。");
const source=(x:WikiItem)=>`${sources[x.section]||x.section} · ${x.collection.replaceAll("-"," ")}`;

export default function Home(){
 const[q,setQ]=useState(""),[type,setType]=useState("全部"),[origin,setOrigin]=useState("全部來源");
 const[selected,setSelected]=useState<WikiItem|null>(null),[tab,setTab]=useState<"browse"|"learn">("browse");
 const[page,setPage]=useState(1),[qi,setQi]=useState(0),[answer,setAnswer]=useState<number|null>(null);
 const filtered=useMemo(()=>wikiItems.filter(x=>{const z=q.trim().toLowerCase();return(!z||x.name.toLowerCase().includes(z)||String(x.id).includes(z)||x.collection.includes(z))&&(type==="全部"||x.type===type)&&(origin==="全部來源"||x.section===origin)}),[q,type,origin]);
 const pool=useMemo(()=>wikiItems.filter(x=>["Cape","Hair","Mask","Outfit","Shoes","HairAccessory"].includes(x.type)&&x.previewUrl),[]);
 const quiz=pool[(qi*37+11)%pool.length];
 const options=useMemo(()=>{const same=pool.filter(x=>x.type===quiz.type&&x.id!==quiz.id);return[quiz,same[(qi*13+5)%same.length],same[(qi*19+9)%same.length]].sort((a,b)=>((a.id+qi)%7)-((b.id+qi)%7))},[quiz,qi,pool]);
 return <main><header className="topbar"><a className="brand" href="#top"><i>✦</i><span>光遇辨識 Wiki</span></a><nav><button className={tab==="browse"?"active":""} onClick={()=>setTab("browse")}>圖鑑</button><button className={tab==="learn"?"active":""} onClick={()=>setTab("learn")}>辨識練習</button></nav></header>
 {tab==="browse"?<><section className="intro" id="top"><div><p className="eyebrow">SKY ITEM FIELD GUIDE</p><h1>先看外型，<br/>再記名字。</h1><p>把工程資料整理成能搜尋、比較、練習的視覺圖鑑。每件物品都保留原始 ID、來源與 Wiki 連結。</p></div><div className="stats"><strong>{wikiItems.length.toLocaleString()}</strong><span>筆可辨識資料</span><strong>{Object.keys(labels).length}</strong><span>種物品分類</span></div></section>
 <section className="workspace"><div className="search-row"><label className="search"><span>⌕</span><input value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="搜尋英文名稱、物品 ID 或季節…"/></label><select value={origin} onChange={e=>{setOrigin(e.target.value);setPage(1)}}>{Object.entries(sources).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>
 <div className="chips">{types.map(x=><button key={x} className={type===x?"selected":""} onClick={()=>{setType(x);setPage(1)}}>{x==="全部"?x:labels[x]}</button>)}</div><div className="result-head"><span>找到 <b>{filtered.length.toLocaleString()}</b> 件</span><small>點選卡片查看辨識重點</small></div>
 {filtered.length?<div className="grid">{filtered.slice(0,page*36).map(x=><button className="item-card" key={x.guid} onClick={()=>setSelected(x)}><div className="image-wrap"><img src={x.icon} alt={x.name} loading="lazy" referrerPolicy="no-referrer"/><span>{labels[x.type]||x.type}</span></div><div className="card-body"><h2>{x.name}</h2><p>{source(x)}</p><small>ID {x.id}</small></div></button>)}</div>:<div className="empty"><b>找不到符合的物品</b><span>試著縮短關鍵字，或清除分類條件。</span></div>}{page*36<filtered.length&&<button className="more" onClick={()=>setPage(x=>x+1)}>載入更多</button>}</section></>
 :<section className="learn-page"><div className="learn-copy"><p className="eyebrow">3-CHOICE PRACTICE</p><h1>看圖選名稱</h1><p>先觀察輪廓與局部特徵，再選答案。答錯也會立即顯示正解。</p><div className="hint"><b>本題辨識提示</b><span>{tip(quiz.type)}</span></div></div><div className="quiz-card"><div className="quiz-image"><img src={quiz.previewUrl} alt="待辨識物品" referrerPolicy="no-referrer"/></div><div className="quiz-meta"><span>{labels[quiz.type]}</span><small>第 {qi+1} 題</small></div><div className="answers">{options.map((x,i)=><button key={x.guid} disabled={answer!==null} onClick={()=>setAnswer(i)} className={answer===null?"":x.id===quiz.id?"correct":answer===i?"wrong":""}>{x.name}</button>)}</div>{answer!==null&&<div className="feedback"><b>{options[answer].id===quiz.id?"答對了":"再看一次，正解已標示"}</b><button onClick={()=>{setQi(x=>x+1);setAnswer(null)}}>下一題 →</button></div>}</div></section>}
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><article className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modal-images"><div><span>衣櫃圖示</span><img src={selected.icon} alt={selected.name} referrerPolicy="no-referrer"/></div>{selected.previewUrl&&<div><span>穿戴／實物預覽</span><img src={selected.previewUrl} alt={`${selected.name} 預覽`} referrerPolicy="no-referrer"/></div>}</div><div className="modal-content"><p className="eyebrow">{labels[selected.type]} · ID {selected.id}</p><h2>{selected.name}</h2><p className="source">{source(selected)}{selected.group?` · ${selected.group}`:""}</p><div className="recognition"><b>怎麼辨識</b><p>{tip(selected.type)}</p></div><dl><div><dt>資料 GUID</dt><dd>{selected.guid}</dd></div><div><dt>原始分類</dt><dd>{selected.type}</dd></div></dl>{selected.wiki&&<a className="wiki-link" href={selected.wiki} target="_blank" rel="noreferrer">查看原始 Wiki ↗</a>}</div></article></div>}
 <footer><span>資料來源：SkyGame-Data 1.3.5、SkyGame-Planner</span><span>非官方粉絲學習工具 · 資料可能隨遊戲更新</span></footer></main>
}
